version: '3'

services:
  app:
    image: openjdk:13
    volumes:
      - .:/var/www
  maven:
    image: maven:3-jdk-13
    volumes:
      - .:/var/www
      - ~/.m2/repository:/root/.m2
    working_dir: /var/www
