openapi: 3.0.1
info:
  title: Pizza Shop
  version: 1.0.0
servers:
- url: https://pizza.shop/v1
- url: http://pizza.shop/v1
tags:
- name: pizza
  description: A round delicious thing usually with cheese on top.
paths:
  /pizzas:
    get:
      tags:
      - pizza
      summary: List pizzas
      operationId: findPizzas
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizza'
components:
  schemas:
    Pizza:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
